package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTel<M extends BaseTel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return getStr("tel");
	}

	public void setTelProvince(java.lang.String telProvince) {
		set("tel_province", telProvince);
	}

	public java.lang.String getTelProvince() {
		return getStr("tel_province");
	}

	public void setTelCity(java.lang.String telCity) {
		set("tel_city", telCity);
	}

	public java.lang.String getTelCity() {
		return getStr("tel_city");
	}

	public void setTelAreaCode(java.lang.String telAreaCode) {
		set("tel_area_code", telAreaCode);
	}

	public java.lang.String getTelAreaCode() {
		return getStr("tel_area_code");
	}

	public void setTelOperator(java.lang.String telOperator) {
		set("tel_operator", telOperator);
	}

	public java.lang.String getTelOperator() {
		return getStr("tel_operator");
	}

	public void setPlatformCollection(java.lang.String platformCollection) {
		set("platform_collection", platformCollection);
	}

	public java.lang.String getPlatformCollection() {
		return getStr("platform_collection");
	}

	public void setAlipayName(java.lang.String alipayName) {
		set("alipay_name", alipayName);
	}

	public java.lang.String getAlipayName() {
		return getStr("alipay_name");
	}

	public void setQqNickname(java.lang.String qqNickname) {
		set("qq_nickname", qqNickname);
	}

	public java.lang.String getQqNickname() {
		return getStr("qq_nickname");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setAge(java.util.Date age) {
		set("age", age);
	}

	public java.util.Date getAge() {
		return get("age");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return getStr("addr");
	}

	public void setCol1(java.lang.String col1) {
		set("col1", col1);
	}

	public java.lang.String getCol1() {
		return getStr("col1");
	}

	public void setCol2(java.lang.String col2) {
		set("col2", col2);
	}

	public java.lang.String getCol2() {
		return getStr("col2");
	}

	public void setCol3(java.lang.String col3) {
		set("col3", col3);
	}

	public java.lang.String getCol3() {
		return getStr("col3");
	}

	public void setCol4(java.lang.String col4) {
		set("col4", col4);
	}

	public java.lang.String getCol4() {
		return getStr("col4");
	}

	public void setCol5(java.lang.String col5) {
		set("col5", col5);
	}

	public java.lang.String getCol5() {
		return getStr("col5");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
