package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMeal<M extends BaseUserMeal<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public void setMealId(java.lang.Long mealId) {
		set("meal_id", mealId);
	}

	public java.lang.Long getMealId() {
		return getLong("meal_id");
	}

	public void setMealName(java.lang.String mealName) {
		set("meal_name", mealName);
	}

	public java.lang.String getMealName() {
		return getStr("meal_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setExpirDate(java.util.Date expirDate) {
		set("expir_date", expirDate);
	}

	public java.util.Date getExpirDate() {
		return get("expir_date");
	}

}
