package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setSoftwareCode(java.lang.String softwareCode) {
		set("software_code", softwareCode);
	}

	public java.lang.String getSoftwareCode() {
		return getStr("software_code");
	}

	public void setSoftwareName(java.lang.String softwareName) {
		set("software_name", softwareName);
	}

	public java.lang.String getSoftwareName() {
		return getStr("software_name");
	}
	
	public void setEnable(java.lang.Boolean enable) {
		set("enable", enable);
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
