package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAccount(java.math.BigDecimal account) {
		set("account", account);
	}

	public java.math.BigDecimal getAccount() {
		return get("account");
	}

	public void setConsumedSum(java.math.BigDecimal consumedSum) {
		set("consumed_sum", consumedSum);
	}

	public java.math.BigDecimal getConsumedSum() {
		return get("consumed_sum");
	}

	public void setLastConsumedTime(java.util.Date lastConsumedTime) {
		set("last_consumed_time", lastConsumedTime);
	}

	public java.util.Date getLastConsumedTime() {
		return get("last_consumed_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return getStr("user_name");
	}

}
