package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("user_pwd", userPwd);
	}

	public java.lang.String getUserPwd() {
		return getStr("user_pwd");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setState(java.lang.Boolean state) {
		set("state", state);
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
	}

	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}

	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public void setAgentId(java.lang.Long agentId) {
		set("agent_id", agentId);
	}

	public java.lang.Long getAgentId() {
		return getLong("agent_id");
	}

	public void setExpirDate(java.util.Date expirDate) {
		set("expir_date", expirDate);
	}

	public java.util.Date getExpirDate() {
		return get("expir_date");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

}
