package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdTask<M extends BaseAdTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setProjectId(java.lang.Long projectId) {
		set("project_id", projectId);
	}

	public java.lang.Long getProjectId() {
		return getLong("project_id");
	}

	public void setBack(java.lang.Boolean back) {
		set("back", back);
	}

	public java.lang.Boolean getBack() {
		return get("back");
	}

	public void setMoeny(java.math.BigDecimal moeny) {
		set("moeny", moeny);
	}

	public java.math.BigDecimal getMoeny() {
		return get("moeny");
	}

	public void setCountCall(java.lang.Integer countCall) {
		set("count_call", countCall);
	}

	public java.lang.Integer getCountCall() {
		return getInt("count_call");
	}

	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}

	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	
	public void setCountCalled(java.lang.Integer countCalled) {
		set("count_called", countCalled);
	}

	public java.lang.Integer getCountCalled() {
		return getInt("count_called");
	}

}
