package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRechargeSet<M extends BaseRechargeSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setRechargeMoney(java.lang.Integer rechargeMoney) {
		set("recharge_money", rechargeMoney);
	}

	public java.lang.Integer getRechargeMoney() {
		return get("recharge_money");
	}

	public void setGive(java.lang.Integer give) {
		set("give", give);
	}

	public java.lang.Integer getGive() {
		return getInt("give");
	}

	public void setGiveRemark(java.lang.String giveRemark) {
		set("give_remark", giveRemark);
	}

	public java.lang.String getGiveRemark() {
		return getStr("give_remark");
	}

	public void setState(java.lang.Boolean state) {
		set("state", state);
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
