package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReportRecharge<M extends BaseReportRecharge<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setReportDate(java.util.Date reportDate) {
		set("report_date", reportDate);
	}

	public java.util.Date getReportDate() {
		return get("report_date");
	}

	public void setSumRechargeMoney(java.math.BigDecimal sumRechargeMoney) {
		set("sum_recharge_money", sumRechargeMoney);
	}

	public java.math.BigDecimal getSumRechargeMoney() {
		return get("sum_recharge_money");
	}

	public void setCountRecharge(java.lang.Integer countRecharge) {
		set("count_recharge", countRecharge);
	}

	public java.lang.Integer getCountRecharge() {
		return getInt("count_recharge");
	}

}
