package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReportInterfaceCall<M extends BaseReportInterfaceCall<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setReportDate(java.util.Date reportDate) {
		set("report_date", reportDate);
	}

	public java.util.Date getReportDate() {
		return get("report_date");
	}

	public void setCountSuccessCall(java.lang.Integer countSuccessCall) {
		set("count_success_call", countSuccessCall);
	}

	public java.lang.Integer getCountSuccessCall() {
		return getInt("count_success_call");
	}

	public void setCountFailCall(java.lang.Integer countFailCall) {
		set("count_fail_call", countFailCall);
	}

	public java.lang.Integer getCountFailCall() {
		return getInt("count_fail_call");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}

	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setProjectPrice(java.math.BigDecimal projectPrice) {
		set("project_price", projectPrice);
	}

	public java.math.BigDecimal getProjectPrice() {
		return get("project_price");
	}

}
