package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTelStatisJob<M extends BaseTelStatisJob<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
	}

	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

	public void setParam(java.lang.String param) {
		set("param", param);
	}

	public java.lang.String getParam() {
		return getStr("param");
	}

}
