package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdTaskDetail<M extends BaseAdTaskDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setQqGroupName(java.lang.String qqGroupName) {
		set("qq_group_name", qqGroupName);
	}

	public java.lang.String getQqGroupName() {
		return getStr("qq_group_name");
	}

	public void setQqGroupNo(java.lang.String qqGroupNo) {
		set("qq_group_no", qqGroupNo);
	}

	public java.lang.String getQqGroupNo() {
		return getStr("qq_group_no");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return getStr("qq");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}

	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}

}
