package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTelCollectionStatis<M extends BaseTelCollectionStatis<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setJobId(java.lang.Long jobId) {
		set("job_id", jobId);
	}

	public java.lang.Long getJobId() {
		return getLong("job_id");
	}

	public void setCollectionType(java.lang.Boolean collectionType) {
		set("collectionType", collectionType);
	}

	public java.lang.Boolean getCollectionType() {
		return get("collectionType");
	}

	public void setPlatform(java.lang.String platform) {
		set("platform", platform);
	}

	public java.lang.String getPlatform() {
		return getStr("platform");
	}

	public void setTelCount(java.lang.Integer telCount) {
		set("telCount", telCount);
	}

	public java.lang.Integer getTelCount() {
		return getInt("telCount");
	}

}
