package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTelCityStatis<M extends BaseTelCityStatis<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setJobId(java.lang.Long jobId) {
		set("job_id", jobId);
	}

	public java.lang.Long getJobId() {
		return getLong("job_id");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setTelCount(java.lang.Integer telCount) {
		set("telCount", telCount);
	}

	public java.lang.Integer getTelCount() {
		return getInt("telCount");
	}

}
