package com.rong.persist.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ocs_account", "id", Account.class);
		arp.addMapping("ocs_ad", "id", Ad.class);
		arp.addMapping("ocs_ad_task", "id", AdTask.class);
		arp.addMapping("ocs_ad_task_detail", "id", AdTaskDetail.class);
		arp.addMapping("ocs_consume", "id", Consume.class);
		arp.addMapping("ocs_interface_call", "id", InterfaceCall.class);
		arp.addMapping("ocs_meal", "id", Meal.class);
		arp.addMapping("ocs_meal_project", "id", MealProject.class);
		arp.addMapping("ocs_notice", "id", Notice.class);
		arp.addMapping("ocs_project", "id", Project.class);
		arp.addMapping("ocs_qq", "id", Qq.class);
		arp.addMapping("ocs_recharge", "id", Recharge.class);
		arp.addMapping("ocs_recharge_set", "id", RechargeSet.class);
		arp.addMapping("ocs_user", "id", User.class);
		arp.addMapping("ocs_user_meal", "id", UserMeal.class);
		arp.addMapping("ocs_user_token", "id", UserToken.class);
		arp.addMapping("report_interface_call", "id", ReportInterfaceCall.class);
		arp.addMapping("report_recharge", "id", ReportRecharge.class);
		arp.addMapping("system_admin", "id", SystemAdmin.class);
		arp.addMapping("system_config", "id", SystemConfig.class);
		arp.addMapping("system_resource", "id", SystemResource.class);
		arp.addMapping("system_role", "id", SystemRole.class);
		arp.addMapping("system_role_resource", "id", SystemRoleResource.class);
		arp.addMapping("tel_city_statis", "id", TelCityStatis.class);
		arp.addMapping("tel_collection_statis", "id", TelCollectionStatis.class);
		arp.addMapping("tel_statis_job", "id", TelStatisJob.class);
	}
}

