package com.rong.persist.model;

import com.rong.persist.model.base.BaseAd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ad extends BaseAd<Ad> {
	public static final Ad dao = new Ad().dao();
	public static final String TABLE = "ocs_ad";
}
