package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdTaskDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdTaskDetail extends BaseAdTaskDetail<AdTaskDetail> {
	public static final AdTaskDetail dao = new AdTaskDetail().dao();
	public static final String TABLE = "ocs_ad_task_detail";
}
