package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdTask extends BaseAdTask<AdTask> {
	public static final AdTask dao = new AdTask().dao();
	public static final String TABLE = "ocs_ad_task";
}
