package com.rong.persist.model;

import com.rong.persist.model.base.BaseConsume;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Consume extends BaseConsume<Consume> {
	public static final Consume dao = new Consume().dao();
	public static final String TABLE = "ocs_consume";
}
