package com.rong.persist.model;

import com.rong.persist.model.base.BaseInterfaceCall;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterfaceCall extends BaseInterfaceCall<InterfaceCall> {
	public static final InterfaceCall dao = new InterfaceCall().dao();
	public static final String TABLE = "ocs_interface_call";
}
