package com.rong.persist.model;

import com.rong.persist.model.base.BaseMealProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MealProject extends BaseMealProject<MealProject> {
	public static final MealProject dao = new MealProject().dao();
	public static final String TABLE = "ocs_meal_project";
}
