package com.rong.persist.model;

import com.rong.persist.model.base.BaseMeal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Meal extends BaseMeal<Meal> {
	public static final Meal dao = new Meal().dao();
	public static final String TABLE = "ocs_meal";
}
