package com.rong.persist.model;

import com.rong.persist.model.base.BaseNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notice extends BaseNotice<Notice> {
	public static final Notice dao = new Notice().dao();
	public static final String TABLE = "ocs_notice";
}
