package com.rong.persist.model;

import com.rong.persist.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	public static final Project dao = new Project().dao();
	public static final String TABLE = "ocs_project";
}
