package com.rong.persist.model;

import com.rong.persist.model.base.BaseQq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Qq extends BaseQq<Qq> {
	public static final Qq dao = new Qq().dao();
	public static final String TABLE = "ocs_qq";
}
