package com.rong.persist.model;

import com.rong.persist.model.base.BaseRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recharge extends BaseRecharge<Recharge> {
	public static final Recharge dao = new Recharge().dao();
	public static final String TABLE = "ocs_recharge";
}
