package com.rong.persist.model;

import com.rong.persist.model.base.BaseRechargeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RechargeSet extends BaseRechargeSet<RechargeSet> {
	public static final RechargeSet dao = new RechargeSet().dao();
	public static final String TABLE = "ocs_recharge_set";
}
