package com.rong.persist.model;

import com.rong.persist.model.base.BaseReportRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportRecharge extends BaseReportRecharge<ReportRecharge> {
	public static final ReportRecharge dao = new ReportRecharge().dao();
	public static final String TABLE = "report_recharge";
}
