package com.rong.persist.model;

import com.rong.persist.model.base.BaseReportInterfaceCall;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportInterfaceCall extends BaseReportInterfaceCall<ReportInterfaceCall> {
	public static final ReportInterfaceCall dao = new ReportInterfaceCall().dao();
	public static final String TABLE = "report_interface_call";
}
