package com.rong.persist.model;

import com.rong.persist.model.base.BaseTel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tel extends BaseTel<Tel> {
	public static final Tel dao = new Tel().dao();
}
