package com.rong.persist.model;

import com.rong.persist.model.base.BaseTelCityStatis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TelCityStatis extends BaseTelCityStatis<TelCityStatis> {
	public static final TelCityStatis dao = new TelCityStatis().dao();
}
