package com.rong.persist.model;

import com.rong.persist.model.base.BaseTelCityStatis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TelCityStatis extends BaseTelCityStatis<TelCityStatis> implements Comparable<TelCityStatis>{
	public static final TelCityStatis dao = new TelCityStatis().dao();

	@Override
	public int compareTo(TelCityStatis item) {
		int i = Integer.parseInt(String.valueOf(item.getTelCount()-this.getTelCount()));//按数量排序  -倒序
        return i;  
	}
}
