package com.rong.persist.model;

import com.rong.persist.model.base.BaseTelCollectionStatis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TelCollectionStatis extends BaseTelCollectionStatis<TelCollectionStatis> {
	public static final TelCollectionStatis dao = new TelCollectionStatis().dao();
}
