package com.rong.persist.model;

import com.rong.persist.model.base.BaseTelStatisJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TelStatisJob extends BaseTelStatisJob<TelStatisJob> {
	public static final TelStatisJob dao = new TelStatisJob().dao();
}
