package com.rong.persist.model;

import com.rong.persist.model.base.BaseUserMeal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMeal extends BaseUserMeal<UserMeal> {
	public static final UserMeal dao = new UserMeal().dao();
	public static final String TABLE = "ocs_user_meal";
}
